FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Copia dependências primeiro
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copia projeto inteiro
COPY . .

# Configurações de ambiente
ENV FLASK_APP="app"
ENV FLASK_RUN_HOST="0.0.0.0"
ENV FLASK_RUN_PORT="5000"
ENV FLASK_ENV="production"

# Aplica migrations
RUN flask db upgrade || true

EXPOSE 5000

# Inicia o servidor usando Gunicorn com Factory Pattern
CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:create_app()"]
